- build.gradle
- src/main/java/com/ajou/hertz/global/config/SwaggerConfig.java
- src/main/resources/application.properties
- Close #1
- Swagger 설정 파일 작성 
- None
> Swagger 설정 파일 작성

- src/main/java/com/ajou/hertz/global/config/WebFilterConfig.java
- src/main/java/com/ajou/hertz/global/logger/Logger.java
- src/main/java/com/ajou/hertz/global/logger/aop/LogTrace.java
- src/main/java/com/ajou/hertz/global/logger/aop/LogTraceAspect.java
- src/main/java/com/ajou/hertz/global/logger/aop/Pointcuts.java
- src/main/java/com/ajou/hertz/global/logger/aop/TraceId.java
- src/main/java/com/ajou/hertz/global/logger/aop/TraceStatus.java
- src/main/java/com/ajou/hertz/global/logger/filter/LogApiInfoFilter.java
- src/main/java/com/ajou/hertz/global/logger/filter/RequestWrapper.java
- src/main/java/com/ajou/hertz/global/logger/filter/ResponseWrapper.java
- src/main/java/com/ajou/hertz/global/logger/util/LogTraceUtils.java
- Close #3
- Logging 시스템 구축
- None
> Logging 시스템 구축

- src/main/java/com/ajou/hertz/global/common/exception/BadRequestException.java
- src/main/java/com/ajou/hertz/global/common/exception/ConflictException.java
- src/main/java/com/ajou/hertz/global/common/exception/CustomException.java
- src/main/java/com/ajou/hertz/global/common/exception/ForbiddenException.java
- src/main/java/com/ajou/hertz/global/common/exception/InternalServerException.java
- src/main/java/com/ajou/hertz/global/common/exception/NotFoundException.java
- src/main/java/com/ajou/hertz/global/common/exception/UnauthorizedException.java
- src/main/java/com/ajou/hertz/global/common/exception/UnprocessableEntityException.java
- src/main/java/com/ajou/hertz/global/exception/GlobalExceptionHandler.java
- src/main/java/com/ajou/hertz/global/exception/constant/CustomExceptionType.java
- src/main/java/com/ajou/hertz/global/exception/constant/GlobalExceptionType.java
- src/main/java/com/ajou/hertz/global/exception/constant/ValidationErrorCode.java
- src/main/java/com/ajou/hertz/global/exception/dto/response/ErrorResponse.java
- src/main/java/com/ajou/hertz/global/exception/dto/response/ValidationErrorDetailResponse.java
- src/main/java/com/ajou/hertz/global/exception/dto/response/ValidationErrorResponse.java
- src/main/java/com/ajou/hertz/global/exception/util/ExceptionUtils.java
- src/main/java/com/ajou/hertz/global/exception/util/ViolationMessageResolver.java
- Close #5 
- Exception handling 시스템 구축
- None
> Exception handling 시스템 구축

- src/main/java/com/ajou/hertz/domain/user/constant/Gender.java
- src/main/java/com/ajou/hertz/domain/user/controller/UserControllerV1.java
- src/main/java/com/ajou/hertz/domain/user/dto/UserDto.java
- src/main/java/com/ajou/hertz/domain/user/dto/request/SignUpRequest.java
- src/main/java/com/ajou/hertz/domain/user/dto/response/UserResponse.java
- src/main/java/com/ajou/hertz/domain/user/entity/User.java
- src/main/java/com/ajou/hertz/domain/user/exception/UserEmailDuplicationException.java
- src/main/java/com/ajou/hertz/domain/user/repository/UserRepository.java
- src/main/java/com/ajou/hertz/domain/user/service/UserCommandService.java
- src/main/java/com/ajou/hertz/domain/user/service/UserQueryService.java
- src/main/java/com/ajou/hertz/global/common/constant/GlobalConstants.java
- src/main/java/com/ajou/hertz/global/common/entity/BaseEntity.java
- src/main/java/com/ajou/hertz/global/common/entity/TimeTrackedBaseEntity.java
- src/main/java/com/ajou/hertz/global/config/JpaConfig.java
- src/main/java/com/ajou/hertz/global/config/SecurityConfig.java
- src/main/java/com/ajou/hertz/global/exception/constant/CustomExceptionType.java
- src/main/java/com/ajou/hertz/global/validator/Password.java
- src/main/java/com/ajou/hertz/global/validator/PasswordValidator.java
- src/test/java/com/ajou/hertz/config/ControllerTestConfig.java
- src/test/java/com/ajou/hertz/config/TestSecurityConfig.java
- src/test/java/com/ajou/hertz/unit/domain/user/controller/UserControllerV1Test.java
- src/test/java/com/ajou/hertz/unit/domain/user/service/UserCommandServiceTest.java
- src/test/java/com/ajou/hertz/unit/domain/user/service/UserQueryServiceTest.java
- Close #7
- Base entity 구현 (with JPA Auditing)
- User entity 구현
- Spring Security 설정
- JPA Auditing 설정
- 회원가입 API 구현
- None
> 회원가입 API 구현

- src/main/java/com/ajou/hertz/domain/user/controller/UserControllerV1.java
- src/main/java/com/ajou/hertz/domain/user/dto/response/UserExistenceResponse.java
- src/main/java/com/ajou/hertz/global/config/SecurityConfig.java
- src/test/java/com/ajou/hertz/unit/domain/user/controller/UserControllerV1Test.java
- Close #8
- 이메일로 회원 존재 여부 조회하기 API 구현
- None
> 이메일로 회원 존재 여부 조회하기 API 구현

- build.gradle
- Close #13
- Jacoco 도입 및 test coverage 설정
- None
> Jacoco 도입 및 test coverage 설정

- build.gradle
- src/main/java/com/ajou/hertz/common/config/AmazonS3Config.java
- src/main/java/com/ajou/hertz/common/entity/FileEntity.java
- src/main/java/com/ajou/hertz/common/exception/MultipartFileNotReadableException.java
- src/main/java/com/ajou/hertz/common/exception/constant/CustomExceptionType.java
- src/main/java/com/ajou/hertz/common/exception/handler/GlobalExceptionHandler.java
- src/main/java/com/ajou/hertz/common/file/dto/FileDto.java
- src/main/java/com/ajou/hertz/common/file/service/AmazonS3FileService.java
- src/main/java/com/ajou/hertz/common/file/service/FileService.java
- src/main/java/com/ajou/hertz/common/properties/AWSProperties.java
- src/main/resources/application.properties
- src/test/java/com/ajou/hertz/HertzApplicationTests.java
- src/test/java/com/ajou/hertz/unit/common/file/service/AmazonS3FileServiceTest.java
- Close #16 
-  AWS S3 bucket 생성 및 설정
- AWS S3 파일 업로드 기능 구현
- [Spring Boot에서 S3에 파일을 업로드하는 세 가지 방법](https://techblog.woowahan.com/11392/)
> AWS S3 파일 업로드 기능 구현

- src/main/java/com/ajou/hertz/common/config/JpaConfig.java
- Close #19
- jpa auditing 임시 설정 작성
- None
> 임시 JPA Auditing 설정 - createdBy, updatedBy

- src/main/java/com/ajou/hertz/HertzApplication.java
- Close #28 
- 서버의 timezone을 "Asia/Seoul"로 설정
- None
> 서버의 timezone을 "Asia/Seoul"로 설정

- src/main/java/com/ajou/hertz/common/properties/HertzProperties.java
- src/main/java/com/ajou/hertz/domain/user/dto/UserDto.java
- src/main/java/com/ajou/hertz/domain/user/dto/response/UserResponse.java
- src/main/java/com/ajou/hertz/domain/user/entity/User.java
- src/main/java/com/ajou/hertz/domain/user/entity/UserProfileImage.java
- src/main/java/com/ajou/hertz/domain/user/service/UserCommandService.java
- src/main/resources/application.properties
- src/test/java/com/ajou/hertz/config/TestSecurityConfig.java
- src/test/java/com/ajou/hertz/unit/common/auth/service/AuthServiceTest.java
- src/test/java/com/ajou/hertz/unit/domain/user/controller/UserControllerV1Test.java
- src/test/java/com/ajou/hertz/unit/domain/user/service/UserCommandServiceTest.java
- src/test/java/com/ajou/hertz/unit/domain/user/service/UserQueryServiceTest.java
- Close #30
- 유저 프로필 이미지 entity 구현
- `User` entity 및 dto class들에 profile image url 필드 추가
- None
> 유저 프로필 이미지 추가

- src/main/java/com/ajou/hertz/domain/instrument/entity/InstrumentBrand.java
- src/main/java/com/ajou/hertz/domain/instrument/entity/InstrumentModel.java
- Close #37
- 악기 브랜드, 모델 엔티티 작성
- None
> 악기 브랜드,모델 엔티티 생성

- src/main/java/com/ajou/hertz/common/entity/Address.java
- src/main/java/com/ajou/hertz/domain/instrument/constant/AcousticAndClassGuitarBrand.java
- src/main/java/com/ajou/hertz/domain/instrument/constant/AcousticAndClassGuitarModel.java
- src/main/java/com/ajou/hertz/domain/instrument/constant/AcousticAndClassGuitarPickUp.java
- src/main/java/com/ajou/hertz/domain/instrument/constant/AcousticAndClassGuitarWood.java
- src/main/java/com/ajou/hertz/domain/instrument/constant/AmplifierBrand.java
- src/main/java/com/ajou/hertz/domain/instrument/constant/AmplifierType.java
- src/main/java/com/ajou/hertz/domain/instrument/constant/AmplifierUsage.java
- src/main/java/com/ajou/hertz/domain/instrument/constant/AudioEquipmentType.java
- src/main/java/com/ajou/hertz/domain/instrument/constant/BassGuitarBrand.java
- src/main/java/com/ajou/hertz/domain/instrument/constant/BassGuitarPickUp.java
- src/main/java/com/ajou/hertz/domain/instrument/constant/BassGuitarPreAmplifier.java
- src/main/java/com/ajou/hertz/domain/instrument/constant/EffectorFeature.java
- src/main/java/com/ajou/hertz/domain/instrument/constant/EffectorType.java
- src/main/java/com/ajou/hertz/domain/instrument/constant/ElectricGuitarBrand.java
- src/main/java/com/ajou/hertz/domain/instrument/constant/ElectricGuitarModel.java
- src/main/java/com/ajou/hertz/domain/instrument/constant/GuitarColor.java
- src/main/java/com/ajou/hertz/domain/instrument/constant/InstrumentCategory.java
- src/main/java/com/ajou/hertz/domain/instrument/constant/InstrumentProgressStatus.java
- src/main/java/com/ajou/hertz/domain/instrument/constant/ProductOrigin.java
- src/main/java/com/ajou/hertz/domain/instrument/entity/AcousticAndClassGuitar.java
- src/main/java/com/ajou/hertz/domain/instrument/entity/Amplifier.java
- src/main/java/com/ajou/hertz/domain/instrument/entity/AudioEquipment.java
- src/main/java/com/ajou/hertz/domain/instrument/entity/BassGuitar.java
- src/main/java/com/ajou/hertz/domain/instrument/entity/Effector.java
- src/main/java/com/ajou/hertz/domain/instrument/entity/ElectricGuitar.java
- src/main/java/com/ajou/hertz/domain/instrument/entity/Instrument.java
- src/main/java/com/ajou/hertz/domain/instrument/entity/InstrumentHashtag.java
- src/main/java/com/ajou/hertz/domain/instrument/entity/InstrumentImage.java
- Close #46
- 악기(`Instrument`) entity 구현
- 악기 이미지 entity 구현
- 악기 해시태그 entity 구현
- None
> 악기 관련 entity 구현

- src/main/java/com/ajou/hertz/domain/instrument/constant/AcousticAndClassicGuitarBrand.java
- src/main/java/com/ajou/hertz/domain/instrument/constant/AcousticAndClassicGuitarModel.java
- src/main/java/com/ajou/hertz/domain/instrument/constant/AcousticAndClassicGuitarPickUp.java
- src/main/java/com/ajou/hertz/domain/instrument/constant/AcousticAndClassicGuitarWood.java
- src/main/java/com/ajou/hertz/domain/instrument/controller/InstrumentControllerV1.java
- src/main/java/com/ajou/hertz/domain/instrument/dto/AcousticAndClassicGuitarDto.java
- src/main/java/com/ajou/hertz/domain/instrument/dto/request/CreateNewAcousticAndClassicGuitarRequest.java
- src/main/java/com/ajou/hertz/domain/instrument/dto/response/AcousticAndClassicGuitarResponse.java
- src/main/java/com/ajou/hertz/domain/instrument/dto/response/BassGuitarResponse.java
- src/main/java/com/ajou/hertz/domain/instrument/entity/AcousticAndClassicGuitar.java
- src/main/java/com/ajou/hertz/domain/instrument/service/InstrumentCommandService.java
- src/main/java/com/ajou/hertz/domain/instrument/strategy/AcousticAndClassicGuitarCreationStrategy.java
- src/test/java/com/ajou/hertz/unit/domain/instrument/controller/InstrumentControllerV1Test.java
- src/test/java/com/ajou/hertz/unit/domain/instrument/service/InstrumentCommandServiceTest.java
- Close #55 
- 어쿠스틱&클래식 기타 매물 생성 API 구현
- None
> 어쿠스틱&클래식 기타 매물 생성 API 구현

- src/main/java/com/ajou/hertz/domain/instrument/controller/InstrumentControllerV1.java
- src/main/java/com/ajou/hertz/domain/instrument/dto/AmplifierDto.java
- src/main/java/com/ajou/hertz/domain/instrument/dto/AudioEquipmentDto.java
- src/main/java/com/ajou/hertz/domain/instrument/dto/EffectorDto.java
- src/main/java/com/ajou/hertz/domain/instrument/dto/request/CreateNewAmplifierRequest.java
- src/main/java/com/ajou/hertz/domain/instrument/dto/request/CreateNewAudioEquipmentRequest.java
- src/main/java/com/ajou/hertz/domain/instrument/dto/request/CreateNewEffectorRequest.java
- src/main/java/com/ajou/hertz/domain/instrument/dto/request/CreateNewInstrumentRequest.java
- src/main/java/com/ajou/hertz/domain/instrument/dto/response/AcousticAndClassicGuitarResponse.java
- src/main/java/com/ajou/hertz/domain/instrument/dto/response/AmplifierResponse.java
- src/main/java/com/ajou/hertz/domain/instrument/dto/response/AudioEquipmentResponse.java
- src/main/java/com/ajou/hertz/domain/instrument/dto/response/EffectorResponse.java
- src/main/java/com/ajou/hertz/domain/instrument/entity/Amplifier.java
- src/main/java/com/ajou/hertz/domain/instrument/service/InstrumentCommandService.java
- src/main/java/com/ajou/hertz/domain/instrument/strategy/AmplifierCreationStrategy.java
- src/main/java/com/ajou/hertz/domain/instrument/strategy/AudioEquipmentCreationStrategy.java
- src/main/java/com/ajou/hertz/domain/instrument/strategy/EffectorCreationStrategy.java
- src/test/java/com/ajou/hertz/unit/domain/instrument/controller/InstrumentControllerV1Test.java
- src/test/java/com/ajou/hertz/unit/domain/instrument/service/InstrumentCommandServiceTest.java
- Close #17
- 이펙터 매물 등록 API 구현
- 앰프 매물 등록 API 구현
- 음향 장비 매물 등록 API 구현
- None
> 중고 악기 매물 생성 API 구현

- build.gradle
- Close #49
- JAXB 경고 문구 대응을 위한 JAXB 의존성 추가
- None
> JAXB 경고 문구 대응

- src/main/java/com/ajou/hertz/common/auth/controller/AuthControllerV1.java
- src/main/java/com/ajou/hertz/common/config/SecurityConfig.java
- src/main/java/com/ajou/hertz/domain/instrument/controller/InstrumentControllerV1.java
- src/main/java/com/ajou/hertz/domain/user/controller/UserControllerV1.java
- src/test/java/com/ajou/hertz/unit/common/auth/controller/AuthControllerV1Test.java
- src/test/java/com/ajou/hertz/unit/domain/instrument/controller/InstrumentControllerV1Test.java
- src/test/java/com/ajou/hertz/unit/domain/user/controller/UserControllerV1Test.java
- Close #60
- API endpoint에 `/api` prefix 추가
- None
> API endpoint에 `/api` prefix 추가

- src/main/java/com/ajou/hertz/common/config/SecurityConfig.java
- src/main/java/com/ajou/hertz/domain/instrument/constant/InstrumentSortOption.java
- src/main/java/com/ajou/hertz/domain/instrument/controller/InstrumentControllerV1.java
- src/main/java/com/ajou/hertz/domain/instrument/dto/response/InstrumentSummaryResponse.java
- src/main/java/com/ajou/hertz/domain/instrument/service/InstrumentQueryService.java
- src/test/java/com/ajou/hertz/unit/domain/instrument/controller/InstrumentControllerV1Test.java
- src/test/java/com/ajou/hertz/unit/domain/instrument/service/InstrumentQueryServiceTest.java
- Close #64
- 전체 악기 매물 목록 조회 API 구현
- None
> 전체 악기 매물 목록 조회 API 구현

- src/main/java/com/ajou/hertz/common/auth/controller/AuthController.java
- src/main/java/com/ajou/hertz/common/config/SecurityConfig.java
- src/main/java/com/ajou/hertz/common/config/SwaggerConfig.java
- src/main/java/com/ajou/hertz/common/constant/GlobalConstants.java
- src/main/java/com/ajou/hertz/domain/administrative_area/controller/AdministrativeAreaController.java
- src/main/java/com/ajou/hertz/domain/instrument/controller/InstrumentController.java
- src/main/java/com/ajou/hertz/domain/user/controller/UserController.java
- src/test/java/com/ajou/hertz/unit/common/auth/controller/AuthControllerTest.java
- src/test/java/com/ajou/hertz/unit/domain/administrative_area/controller/AdministrativeAreaControllerTest.java
- src/test/java/com/ajou/hertz/unit/domain/instrument/controller/InstrumentControllerTest.java
- src/test/java/com/ajou/hertz/unit/domain/user/controller/UserControllerTest.java
- Close #68
-  API endpoint에 표현된 major 버전 제거
- Swagger 명세에 API 버전 정책 설명 추가 (토스페이먼츠 API 버전 정책 참고)
- [토스페이먼츠 - API 버전 정책](https://docs.tosspayments.com/reference/versioning#api-%EB%B2%84%EC%A0%84-%EC%A0%95%EC%B1%85)
> API versioning 정책 변경

- src/test/java/com/ajou/hertz/config/TestSecurityConfig.java
- src/test/java/com/ajou/hertz/integration/domain/instrument/repository/InstrumentRepositoryTest.java
- src/test/java/com/ajou/hertz/unit/common/auth/controller/AuthControllerTest.java
- src/test/java/com/ajou/hertz/unit/common/auth/service/AuthServiceTest.java
- src/test/java/com/ajou/hertz/unit/common/kakao/service/KakaoServiceTest.java
- src/test/java/com/ajou/hertz/unit/domain/administrative_area/controller/AdministrativeAreaControllerTest.java
- src/test/java/com/ajou/hertz/unit/domain/instrument/controller/InstrumentControllerTest.java
- src/test/java/com/ajou/hertz/unit/domain/instrument/service/InstrumentCommandServiceTest.java
- src/test/java/com/ajou/hertz/unit/domain/instrument/service/InstrumentQueryServiceTest.java
- src/test/java/com/ajou/hertz/unit/domain/user/controller/UserControllerTest.java
- src/test/java/com/ajou/hertz/unit/domain/user/service/UserCommandServiceTest.java
- src/test/java/com/ajou/hertz/unit/domain/user/service/UserQueryServiceTest.java
- src/test/java/com/ajou/hertz/util/ReflectionUtils.java
- Close #76
- 테스트 관련 Reflection 사용 코드 개선
- None
> 테스트 관련 Reflection 사용 코드 개선

- src/main/java/com/ajou/hertz/domain/instrument/constant/InstrumentCategory.java
- src/main/java/com/ajou/hertz/domain/instrument/controller/InstrumentController.java
- src/main/java/com/ajou/hertz/domain/instrument/dto/AcousticAndClassicGuitarDto.java
- src/main/java/com/ajou/hertz/domain/instrument/dto/AmplifierDto.java
- src/main/java/com/ajou/hertz/domain/instrument/dto/AudioEquipmentDto.java
- src/main/java/com/ajou/hertz/domain/instrument/dto/BassGuitarDto.java
- src/main/java/com/ajou/hertz/domain/instrument/dto/EffectorDto.java
- src/main/java/com/ajou/hertz/domain/instrument/dto/ElectricGuitarDto.java
- src/main/java/com/ajou/hertz/domain/instrument/dto/InstrumentDto.java
- src/main/java/com/ajou/hertz/domain/instrument/dto/response/AcousticAndClassicGuitarResponse.java
- src/main/java/com/ajou/hertz/domain/instrument/dto/response/AmplifierResponse.java
- src/main/java/com/ajou/hertz/domain/instrument/dto/response/AudioEquipmentResponse.java
- src/main/java/com/ajou/hertz/domain/instrument/dto/response/BassGuitarResponse.java
- src/main/java/com/ajou/hertz/domain/instrument/dto/response/EffectorResponse.java
- src/main/java/com/ajou/hertz/domain/instrument/dto/response/ElectricGuitarResponse.java
- src/main/java/com/ajou/hertz/domain/instrument/dto/response/InstrumentResponse.java
- src/main/java/com/ajou/hertz/domain/instrument/dto/response/InstrumentSummaryResponse.java
- src/test/java/com/ajou/hertz/unit/domain/instrument/controller/InstrumentControllerTest.java
- src/test/java/com/ajou/hertz/unit/domain/instrument/service/InstrumentQueryServiceTest.java
- src/test/java/com/ajou/hertz/util/ReflectionUtils.java
- Close #80
- 악기 API 응답 정보 및 DTO에 카테고리 필드 추가
- None
> 악기 API 응답 정보에 카테고리 추가

- src/main/java/com/ajou/hertz/common/exception/constant/CustomExceptionType.java
- src/main/java/com/ajou/hertz/domain/instrument/controller/InstrumentController.java
- src/main/java/com/ajou/hertz/domain/instrument/dto/request/InstrumentUpdateRequest.java
- src/main/java/com/ajou/hertz/domain/instrument/electric_guitar/dto/request/CreateNewElectricGuitarRequest.java
- src/main/java/com/ajou/hertz/domain/instrument/electric_guitar/dto/request/ElectricGuitarUpdateRequest.java
- src/main/java/com/ajou/hertz/domain/instrument/electric_guitar/entity/ElectricGuitar.java
- src/main/java/com/ajou/hertz/domain/instrument/entity/Instrument.java
- src/main/java/com/ajou/hertz/domain/instrument/entity/InstrumentHashtags.java
- src/main/java/com/ajou/hertz/domain/instrument/entity/InstrumentImages.java
- src/main/java/com/ajou/hertz/domain/instrument/exception/InstrumentUpdatePermissionDeniedException.java
- src/main/java/com/ajou/hertz/domain/instrument/repository/InstrumentImageRepository.java
- src/main/java/com/ajou/hertz/domain/instrument/repository/InstrumentRepositoryCustom.java
- src/main/java/com/ajou/hertz/domain/instrument/repository/InstrumentRepositoryCustomImpl.java
- src/main/java/com/ajou/hertz/domain/instrument/service/InstrumentCommandService.java
- src/main/java/com/ajou/hertz/domain/instrument/service/InstrumentHashtagCommandService.java
- src/main/java/com/ajou/hertz/domain/instrument/service/InstrumentImageCommandService.java
- src/main/java/com/ajou/hertz/domain/instrument/service/InstrumentQueryService.java
- src/test/java/com/ajou/hertz/integration/domain/instrument/repository/InstrumentRepositoryTest.java
- src/test/java/com/ajou/hertz/unit/domain/instrument/controller/InstrumentControllerTest.java
- src/test/java/com/ajou/hertz/unit/domain/instrument/service/InstrumentCommandServiceTest.java
- src/test/java/com/ajou/hertz/unit/domain/instrument/service/InstrumentHashtagCommandServiceTest.java
- src/test/java/com/ajou/hertz/unit/domain/instrument/service/InstrumentImageCommandServiceTest.java
- src/test/java/com/ajou/hertz/unit/domain/instrument/service/InstrumentQueryServiceTest.java
- src/test/java/com/ajou/hertz/util/ReflectionUtils.java
- #71
- 일렉 기타 매물 정보 수정 API 구현
- None
> 일렉 기타 매물 정보 수정 API 구현
